# Generated by Django 5.2.17 on 2026-09-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('AJUSTE', 'Ajuste de estoque'), ('DEVOLUCAO', 'Devolução'), ('OUTRO', 'Outro')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
    ]
