# Generated by Django 5.2.17 on 2026-09-11 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_minimo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sku',
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('tamanho', models.CharField(blank=True, max_length=20)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
            ],
        ),
    ]
