# Generated by Django 5.2.17 on 2026-09-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0002_remove_produto_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variacoes_produtos', to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='variacaoproduto',
            constraint=models.UniqueConstraint(fields=('empresa', 'sku'), name='unique_sku_por_empresa'),
        ),
    ]
