# Generated by Django 5.2.17 on 2026-10-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('acessar_dashboard', 'Pode acessar o dashboard')]},
        ),
    ]
