# Generated by Django 5.2.17 on 2026-10-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('acessar_dashboard', 'Pode acessar o dashboard'), ('acessar_vendas', 'Pode acessar vendas'), ('acessar_produtos', 'Pode acessar produtos'), ('acessar_estoque', 'Pode acessar estoque'), ('acessar_clientes', 'Pode acessar clientes'), ('acessar_compras', 'Pode acessar compras'), ('acessar_fornecedores', 'Pode acessar fornecedores'), ('acessar_financeiro', 'Pode acessar financeiro')]},
        ),
    ]
