# Generated by Django 5.2.17 on 2026-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
